shop:
  label: My shop info
  fields:
    address:
      type: text
      hint: "Ex: 5555 Love Paradise 56 New Clity 5655,<br>Excel Tower United Kingdom"
    tel:
      type: string
      hint: "(123) 465-6789"
    mail:
      type: string
      hint: "info@html5"
    hours:
      type: text
      hint: "Free text here"
social:
  label: Social links
  fields:
    facebook:
      type: string
    twitter:
      type: string
    instagram:
      type: string
