name: "foodee"
locales: [en]
timezone: Paris
seo_title: foodee
meta_keywords: "some meta keywords"
meta_description: "some meta description"
metafields_ui:
  label: Settings
  icon: home
metafields:
  shop:
    address: 5555 Love Paradise 56 New Clity 5655,<br>Excel Tower United Kingdom
    tel: (123) 465-6789
    mail: info@html5
  social:
    facebook: "#"
    twitter: "#"
    instagram: "#"
